### ISSUE TITLE
Interaction with HighVoltage pages

### ISSUE THREAD

**Issue by tute** [calebthompson/title#10]
Through `pages#show`, High Voltage shows different static pages in Rails apps. I'd like to [define a different title to each](https://github.com/thoughtbot/suspenders/issues/600), but for that to happen `title` would need to accept the page name (`id`) as locale key. Do you think `title` should do that?
Thank you!

**Comment by tute** [comment]
ping @calebthompson

**Comment by calebthompson** [comment]
I agree that https://github.com/thoughtbot/suspenders/issues/600#issuecomment-133736226 should work.

I can't think offhand of a clean way to do that.

**Comment by calebthompson** [comment]
Generally my answer for HV has been to use flutie's page_title helper.

**Comment by tute** [comment]
Right! `@title_options = { page_title: params[:id].capitalize }`, or whatever.

**Comment by tute** [comment]
I'm happy with that, will close this issue. Thanks!

**Comment by calebthompson** [comment]
That only works if the slug is what you want :/

**Comment by calebthompson** [comment]
For this stumbling on this in the future, this is an ivar Suspenders passes into title, so basically just additional_context in title parlance.
