### ISSUE TITLE
Can you override title?

### ISSUE THREAD

**Issue by moubry** [calebthompson/title#14]
Is there a way to override Title’s title from either inside a view or controller?

This is a contrived example, but let’s say a user wants to view something they’re not allowed to — a page rendered by a `show` action in a `PrivateThingsController`. In a `before_action` I'm making sure the user is authorized to view the thing, and if they’re not, then I’m immediately rendering an unauthorized error page template, along with the `views/layouts/application.html.erb` layout.

For reference, this would be the I18n file in this situation:

```
titles:
  private_things:
    show: "%{private_thing} - ApplicationName"
```

This results in a `I18n::MissingInterpolationArgument` since the variable is not set. The problem is that zero code from the `show` action actually gets executed — is it possible to override title in the event that the error template gets rendered and have the title say “403 Forbidden” instead?

I know I could redirect to an error page, and avoid this issue, but I’d prefer the request to respond with a 403.

I love title. Thank you for making it.

**Comment by moubry** [comment]
For anyone that stumbles across this in the future, this is the way I’m currently solving this problem...

My application layout:

```html
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
  <title><%= content_for?(:page_title) ? yield(:page_title) : title %></title>
...
```

My `error.html.erb` template:

```
<% content_for :page_title, t("titles.errors.error_#{response.status}") %>
```

My `en.yml` file:

```
  titles:
    errors:
      error_401: Unauthorized
```

**Comment by calebthompson** [comment]
Do you have a proposal for an API that would be consistent with how Title currently works for this?

**Comment by moubry** [comment]
Honestly, I’m not sure. I can’t decide if there’s a general need here (to override title) or a specific need to I18n the titles of error pages. Either way, I admittedly can’t think of a great API (that's consistent with how Title currently works). I’m happy with this pattern I’m using for overriding title within my application's view/layout itself. Perhaps the best thing to do for this issue is to close it?

**Comment by calebthompson** [comment]
I think I agree, but I wonder if there's something to be done with object interpolation? An error object maybe, whose to_s gives a useful title?
