### ISSUE TITLE
Create and Update actions should fall back to titles for New and Edit

### ISSUE THREAD

**Issue by derekprior** [calebthompson/title#7]
When a create or update action is invalid it usually renders the new or edit template respectively. It seems like a sane default for those titles would be to fall back to new and create actions. What do you think?

**Comment by calebthompson** [comment]
See #1. I was thinking about this last night and it could possibly be simpler than I expected back then.

I'd accept any PR whose complexity didn't outweigh the (weighty) benefit of this improvement.

**Comment by calebthompson** [comment]
There's also #5 which I never really got around to reviewing.
