### ISSUE TITLE
An option to automatically append application name and separator to translated strings

### ISSUE THREAD

**Issue by pineapplethief** [calebthompson/title#9]
I've noticed that I almost always want my titles in form of 
```Ruby
"#{translated_action}#{separator}#{application_name}"
```
with a fallback to just application_name if locale for translated_action not found.
Perhaps title method could take additional options hash to handle stuff like setting application_name, separator (' - ' as default) and a flag to enable this feature.
It would be great to configure gem to allow behaviour of this sort. For now I just copied code to helper in app, but I guess I could prepare a PR.

**Comment by SirRawlins** [comment]
+1 this would be great.

**Comment by calebthompson** [comment]
I'd be happy to look at a PR. I think this has been requested before.

Probably an argument to the helper?

**Comment by tute** [comment]
> Probably an argument to the helper?

Or a global configuration option, set in an initializer?

**Comment by calebthompson** [comment]
I'd rather start with the helper argument and see if we really need an initializer. There's a lot more code involved with that.
